name:                yapb
version:             0.2.2
github:              "kwanghoon/yapb"
license:             BSD3
author:              "Kwanghoon Choi"
maintainer:          "lazyswamp@gmail.com"
copyright:           "2020-2021 Kwanghoon Choi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Yet Another Parser Builder (YAPB)
category:            parser builder

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A programmable LALR(1) parser builder system. Please see the README on GitHub at <https://github.com/kwanghoon/yapb#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- transformers
- mtl
- deepseq >= 1.4.4.0

# --------------------------------------------------
# -- Main library: YAPB (Yet Another Parser Builder)
# --------------------------------------------------
library:
  source-dirs:
   - src/gentable/
   - src/parserlib/
   - src/parserlib/algo
   - src/syncomplib
   - src/util/
   - src/config/
  exposed-modules:
   - CFG
   - Attrs
   - CmdArgs
   - ParserTable
   - GenLRParserTable
   - SampleGrammar
   - CodeGenC
   - TokenInterface
   - Terminal
   - CommonParserUtil
   - SaveProdRules
   - AutomatonType
   - LoadAutomaton
   - ReadGrammar
   - EmacsServer
   - SynCompInterface
   - Config
   - SynCompAlgoBU
   - SynCompAlgoBUTree
   - SynCompAlgoBUTreeNested
   - SynCompAlgoTD
   - SynCompAlgoPEPM
   - SynCompAlgoUtil
   - SynCompAlgorithm

  dependencies:
  - regex-tdfa    >= 1.3.1 && < 1.4
  - hashable      >= 1.3.0 && < 1.4
  - directory     >= 1.3.3 && < 1.4
  - process       >= 1.6.5 && < 1.7
  - network     >= 3.1.1 && < 3.2     # for syntax completion library
  - bytestring  >= 0.10.8 && < 0.11
   

executables:
# ----------------------------------------
# -- Utility1: A wrapper interface to YAPB
# ----------------------------------------
  yapb-exe:
    main:                Main.hs
    source-dirs:         app/yapb
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yapb

# ------------------------------------------------------------------------------------
# -- Utility2: A grammar converter utility of a readable form into a Haskell data form
# -------------------------------------------------------------------------------------
  conv-exe:
    main:                Main.hs
    source-dirs:         app/conv
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yapb

# ----------------------------------------
# -- Utiliyt3: A syntax completion server
# ----------------------------------------
  syncomp-exe:
    main:                Main.hs
    source-dirs:
    - app/syntaxcompletion
    - app/syntaxcompletion/ast
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-tdfa
    - yapb

# ---------------------------------
# -- Example1: An arithmetic parser
# ---------------------------------
  parser-exe:
    main:                Main.hs
    
    source-dirs:
    - app/parser
    - app/parser/ast
    
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-tdfa
    - yapb

# ---------------------------------
# -- Example2: An ambiguous parser
# ---------------------------------
  ambiguous-exe:
    main:                Main.hs
    
    source-dirs:
    - app/ambiguous
    - app/ambiguous/ast
    
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-tdfa
    - yapb

# ---------------------------------
# -- Example3: An error handling
# ---------------------------------
  error-exe:
    main:                Main.hs
    
    source-dirs:
    - app/error
    - app/error/ast
    
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-tdfa
    - yapb

tests:
  yapb-test:
    main:                Spec.hs
    source-dirs:         
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yapb
    - process
